! HQ Layer-2 switch
enable
configure terminal

hostname SW-HQ-LAN

vlan 10
 name HQ-LAN
exit

interface range g0/0 - 3
 switchport mode access
 switchport access vlan 10
 no shutdown
exit

interface range g1/0 - 3
 switchport mode access
 switchport access vlan 10
 no shutdown
exit

end
write
